name: ci

on:
  push:
    branches: ["main", "release-*"]
  pull_request:

jobs:
  test:
    strategy:
      matrix:
        os:
          - macos-latest
          - windows-latest
          - ubuntu-latest
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 90

    env:
      CARGO_TERM_COLOR: always
      RUST_BACKTRACE: full
      RUSTC_FORCE_INCREMENTAL: 1

    steps:
      - name: Clone repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 5
          submodules: recursive
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Install Rust
        uses: hecrj/setup-rust-action@v1
        with:
          rust-version: 1.57.0

      - name: Runner test
        run: |
          cargo test
